### ISSUE TITLE
Invalid test case

### ISSUE THREAD

**Issue by Galya-IT** [wisetime-io/wisetime-inprotech-connector#15]
This case is invalid, have to be removed: https://github.com/wisetime-io/wisetime-inprotech-connector/blob/f77a34d5822687d405dd57d32165288046a205ef/src/test/java/io/wisetime/connector/inprotech/InprotechConnectorPostTimeTest.java#L174

It passes for other reasons: `All time logs within time group should have same modifier, but got: [molestiae, qui, accusantium, nisi, non]`

If a case is not found, it's just skipped. No `PostResult.PERMANENT_FAILURE` is returned.

**Comment by alvinllobrera** [comment]
fixed!
