### ISSUE TITLE
Rename `Total chargeable time` to `Total posted time` in TimeGroup narrative template

### ISSUE THREAD

**Issue by Galya-IT** [wisetime-io/wisetime-inprotech-connector#16]
This is basically not correct, since the `Total chargeable time` is calculated with a complex formula in  `DurationCalculator`:
https://github.com/wisetime-io/wisetime-inprotech-connector/blob/f77a34d5822687d405dd57d32165288046a205ef/src/main/resources/inprotech-template.ftl#L12

It should be named `Total posted time`.

**Comment by alvinllobrera** [comment]
Fixed on https://github.com/wisetime-io/wisetime-inprotech-connector/pull/18
